library(tidyverse)
vaccines <- read_csv("https://raw.githubusercontent.com/govex/COVID-19/master/data_tables/vaccine_data/global_data/time_series_covid19_vaccine_doses_admin_global.csv")
beds <- read_csv("data.csv")
demographics <- read_csv("demographics.csv")
vaccines <- vaccines %>% select(-c(FIPS, Admin2, Province_State, code3, iso3, iso2, UID, Lat, Long_, Combined_Key), Country = Country_Region)
vaccines <- vaccines %>% pivot_longer(3:473, names_to = "Date", values_to = "Shots", values_drop_na = TRUE) %>% filter(Shots != 0) %>% group_by(Country) %>% mutate(vacRate = Shots/Population, daysSinceStart = row_number()) %>% ungroup() %>% select(Country, vacRate, Shots, Population, daysSinceStart)
vaccines <- vaccines %>% mutate(Country = replace(Country, Country == "Korea, South", "South Korea"))
vaccines <- vaccines %>% mutate(Country = replace(Country, Country == "US", "United States"))
beds <- beds %>% group_by(Country) %>% filter(Year == max(Year)) %>% select(Country, Beds = `Hospital beds (per 10 000 population)`)
beds <- beds %>% mutate(Country = replace(Country, Country == "Democratic People's Republic of Korea", "South Korea"))
beds <- beds %>% mutate(Country = replace(Country, Country == "Republic of Korea", "South Korea"))
beds <- beds %>% mutate(Country = replace(Country, Country == "United Kingdom of Great Britain and Northern Ireland", "United Kingdom"))
beds <- beds %>% mutate(Country = replace(Country, Country == "Iran (Islamic Republic of)", "Iran"))
beds <- beds %>% mutate(Country = replace(Country, Country == "United States of America", "United States"))
demographics <- demographics %>% pivot_wider(-'Series Name', names_from = `Series Code`, values_from = YR2015) %>% mutate(SP.POP.80UP.TOTL = SP.POP.80UP.FE + SP.POP.80UP.MA, SP.POP.1564.TOTL = SP.POP.1564.MA.IN + SP.POP.1564.FE.IN, SP.POP.0014.TOTL = SP.POP.0014.MA.IN + SP.POP.0014.FE.IN, SP.DYN.AMRT.TOTL = SP.DYN.AMRT.FE + SP.DYN.AMRT.MA, SP.POP.TOTL.TOTL = SP.POP.TOTL.FE.IN + SP.POP.TOTL.MA.IN, SP.POP.65UP.TOTL = SP.POP.65UP.FE.IN + SP.POP.65UP.MA.IN) %>% select(Country = `Country Name`, 3:5, 18:23)
demographics <- demographics %>% mutate(Country = replace(Country, Country == "Korea, Dem. People’s Rep.", "South Korea"))
demographics <- demographics %>% mutate(Country = replace(Country, Country == "Korea, Rep.", "South Korea"))
demographics <- demographics %>% mutate(Country = replace(Country, Country == "Iran, Islamic Rep.", "Iran"))
vaxData <- vaccines %>% inner_join(beds) %>% inner_join(demographics)